### ISSUE TITLE
Suggestion - Create a Fabric version?

### ISSUE THREAD

**Issue by DillonB07** [PotatoSauceVFX/Whitelist-Sync-2#14]
Hi,

First of all, great mod. It's really useful and will help a lot!
Would you please consider creating a version for [Fabric](https://fabricmc.net)?
Completely understand if you don't, but Fabric is a great mod-loader and is used more for servers than Forge is. (On account of more Fabric mods being serverside than on Forge).

Thanks

**Comment by PotatoSauceVFX** [comment]
@dbarnes18 I would be happy to look into making a fabric version. I have not used fabric, but I have heard a lot about it.

Thank you for your suggestion. I will let you know when it is available for download.

**Comment by Foxite** [comment]
Have you started working on this yet? If not, I'm happy to get it done.

**Comment by PotatoSauceVFX** [comment]
@Foxite I have not and I don't know anything about Fabric. You are welcome to work on it.
