### ISSUE TITLE
MySQL Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by jordankothe9** [PotatoSauceVFX/Whitelist-Sync-2#19]
I've setup the spigot version of this mod/plugin with no issues and the database is able to be accessed. When I got to install the forge 1.16.5 version it does not work. I get an error. I'm no DB expert but most google results for Public-key retrieval not allow points to an issue with the mod. It is possible my DB is not configured correctly.

Here is my console output:

[11:50:17] [Server thread/INFO]: ----------------------------------------------
[11:50:17] [Server thread/INFO]: ---------------WHITELIST SYNC 2---------------
[11:50:17] [Server thread/INFO]: ----------------------------------------------
[11:50:17] [Server thread/INFO]: Setting up the MySQL service...
[11:50:17] [Server thread/ERROR]: Failed to connect to the mySQL database! Did you set one up in the config?
[11:50:17] [Server thread/ERROR]: Public Key Retrieval is not allowed
java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[whitelistsync2:1.16.5-2.2.5]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[whitelistsync2:1.16.5-2.2.5]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_312]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_312]
	at pw.twpi.whitelistsync2.services.MySqlService.initializeDatabase(MySqlService.java:63) ~[whitelistsync2:1.16.5-2.2.5]
	at pw.twpi.whitelistsync2.WhitelistSync2.onServerStarting(WhitelistSync2.java:65) ~[whitelistsync2:1.16.5-2.2.5]
	at net.minecraftforge.eventbus.ASMEventHandler_472_WhitelistSync2_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:101) ~[forge:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11:50:17] [Server thread/ERROR]: Error initializing whitelist sync database. Disabling mod functionality. Please correct errors and restart.
[11:50:17] [Server thread/INFO]: ----------------------------------------------
[11:50:17] [Server thread/INFO]: ----------------------------------------------
[11:50:17] [Server thread/INFO]: ----------------------------------------------

**Comment by jordankothe9** [comment]
Also here's my mod list. I'm using the Vault Hunters modpack. I'm not sure if there could be an incompatablity.

[11:51:42] [Server thread/INFO]: Mod List: 
• mods_folder rsrequestify-1.16.5-2.1.4.jar : rsrequestify (2.1.4) - 1
• mods_folder mcw-windows-2.0.2-mc1.16.5.jar : mcwwindows (2.0.2) - 1
• mods_folder torohealth-1.16.4-forge-4.jar : torohealth (NONE) - 1
• mods_folder rsgauges-1.16.5-1.2.13.jar : rsgauges (1.2.13) - 1
• mods_folder IronJetpacks-1.16.5-4.2.3.jar : ironjetpacks (4.2.3) - 1
• mods_folder XaerosWorldMap_1.16.0_Forge_1.16.5.jar : xaeroworldmap (1.16.0) - 1
• mods_folder CookingForBlockheads_1.16.5-9.3.4.jar : cookingforblockheads (9.3.4) - 1
• mods_folder Controlling-7.0.0.28.jar : controlling (7.0.0.28) - 1
• mods_folder Placebo-1.16.5-4.6.1.jar : placebo (4.6.1) - 1
• mods_folder dankstorage-3.19.jar : dankstorage (3.19) - 1
• mods_folder Powah-1.16.5-2.3.16.jar : powah (2.3.16) - 1
• mods_folder rangedpumps-0.8.2.jar : rangedpumps (0.8.2) - 1
• mods_folder Bookshelf-Forge-1.16.5-10.3.29.jar : bookshelf (10.3.29) - 1
• mods_folder u_team_core-1.16.5-3.2.1.196.jar : uteamcore (3.2.1.196) - 1
• mods_folder buildinggadgets-1.16.5-3.8.2.jar : buildinggadgets (3.8.2) - 1
• mods_folder mcw-doors-1.0.5-mc1.16.5.jar : mcwdoors (1.0.5) - 1
• mods_folder Morpheus-1.16.5-4.2.70.jar : morpheus (4.2.70) - 1
• mods_folder MekanismGenerators-1.16.5-10.1.1.456.jar : mekanismgenerators (10.1.1) - 1
• mods_folder Hwyla-forge-1.10.11-B78_1.16.2.jar : waila (1.10.11-B78_1.16.2) - 1
• mods_folder JustEnoughResources-1.16.5-0.12.1.133.jar : jeresources (0.12.1.133) - 1
• mods_folder shetiphiancore-1.16-3.8.6.jar : shetiphiancore (3.8.6) - 1
• mods_folder MmmMmmMmmMmm-1.16.5-1.3.1.jar : dummmmmmy (1.3.0) - 1
• mods_folder dcintegration-forge-2.3.1-1.16.jar : dcintegration (2.3.1) - 1
• mods_folder supplementaries-1.16.5-0.18.0.jar : supplementaries (0.18.0) - 1
• mods_folder refinedstorage-1.9.15.jar : refinedstorage (1.9.15) - 1
• mods_folder PrettyPipes-1.9.5.jar : prettypipes (1.9.5) - 1
• mods_folder corpse-1.16.5-1.0.6.jar : corpse (1.16.5-1.0.6) - 1
• mods_folder mcw-bridges-2.0.1-mc1.16.5.jar : mcwbridges (2.0.1) - 1
• mods_folder industrial-foregoing-1.16.5-3.2.14.6-14.jar : industrialforegoing (3.2.14.6) - 1
• mods_folder torchmaster-2.3.8.jar : torchmaster (2.3.8) - 1
• mods_folder Compressium-1.16.5-1.2.3.jar : compressium (1.2.custom) - 1
• mods_folder valkyrielib-1.16.5-3.0.9.5.jar : valkyrielib (1.16.5-3.0.9.5) - 1
• mods_folder Lollipop-1.16.5-3.2.9.jar : lollipop (3.2.9) - 1
• mods_folder ironfurnaces-1.16.5-2.7.7.jar : ironfurnaces (2.7.7) - 1
• mods_folder supermartijn642corelib-1.0.16-mc1.16.5.jar : supermartijn642corelib (1.0.16) - 1
• mods_folder masonry-1.16.3-0.3.6.jar : masonry (NONE) - 1
• mods_folder simplylight-1.16.5-1.4.0-build.24.jar : simplylight (1.16.5-1.4.0-build.24) - 1
• mods_folder Botania-1.16.5-420.1.jar : botania (1.16.5-420.1) - 1
• mods_folder fairylights-4.0.5-1.16.5.jar : fairylights (4.0.5) - 1
• mods_folder simplybackpacks-1.16.5-2.0.1-build.27.jar : simplybackpacks (1.16.5-2.0.1-build.27) - 1
• mods_folder curios-forge-1.16.5-4.0.5.2.jar : curios (1.16.5-4.0.5.2) - 1
• mods_folder Patchouli-1.16.4-53.2.jar : patchouli (1.16.4-53.2) - 1
• mods_folder camera-1.16.5-1.0.14.jar : camera (1.16.5-1.0.14) - 1
• mods_folder blockcarpentry-1.16-0.4.0.jar : blockcarpentry (1.16-0.4.0) - 1
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder neoncraft-2.1.jar : neoncraft (2.1) - 1
• mods_folder Runelic-1.16.5-7.0.2.jar : runelic (7.0.2) - 1
• mods_folder DarkUtilities-1.16.3-6.0.3.jar : darkutils (6.0.3) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
• mods_folder architectury-1.28.48.jar : architectury (1.28.48) - 1
• mods_folder mcw-furniture-2.0.1-mc1.16.5.jar : mcwfurnitures (2.0.1) - 1
• mods_folder trashcans-1.0.11-mc1.16.jar : trashcans (1.0.11) - 1
• mods_folder Cucumber-1.16.5-4.1.12.jar : cucumber (4.1.12) - 1
• mods_folder ftb-library-forge-1605.3.4-build.90.jar : ftblibrary (1605.3.4-build.90) - 1
• mods_folder snad-1.0.9-forge.jar : snad (1.0.9) - 1
• mods_folder platforms-1.16-1.7.12.jar : platforms (1.7.12) - 1
• mods_folder jei-1.16.5-7.7.1.139.jar : jei (7.7.1.139) - 1
• mods_folder metalbarrels-1.16.2-3.3b.jar : metalbarrels (1.16.2-3.3b) - 1
• mods_folder invtweaks-1.16.4-1.0.1.jar : invtweaks (1.16.4-1.0.1) - 1
• mods_folder Waystones_1.16.5-7.6.4.jar : waystones (7.6.4) - 1
• mods_folder Clumps-6.0.0.27.jar : clumps (6.0.0.27) - 1
• mods_folder enviromats-1.16.5-2.0.9.0.jar : enviromats (2.0.9.0) - 1
• mods_folder comforts-forge-1.16.5-4.0.1.3.jar : comforts (1.16.5-4.0.1.3) - 1
• mods_folder appliedenergistics2-8.4.6.jar : appliedenergistics2 (8.4.6) - 1
• mods_folder framedcompactdrawers-1.16-2.2.1.jar : framedcompactdrawers (1.16-2.2.1) - 1
• mods_folder DimStorage-1.16.5-4.4.1.jar : dimstorage (4.4.1) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder mcjtylib-1.16-5.1.2.jar : mcjtylib (1.16-5.1.2) - 1
• mods_folder rftoolsbase-1.16-2.1.1.jar : rftoolsbase (1.16-2.1.1) - 1
• mods_folder xnet-1.16-3.0.15.jar : xnet (1.16-3.0.15) - 1
• mods_folder rftoolsstorage-1.16-2.0.15.jar : rftoolsstorage (1.16-2.0.15) - 1
• mods_folder ispawner-0.1.7-forge.jar : ispawner (1.0) - 1
• mods_folder JEITweaker-1.16.5-1.1.0.49.jar : jeitweaker (1.1.0.49) - 1
• mods_folder mininggadgets-1.7.5.jar : mininggadgets (1.7.5) - 1
• mods_folder entitydetectors-1.16.4-1.1.0.1.jar : entitydetectors (1.1.0.1) - 1
• mods_folder CraftTweaker-1.16.5-7.1.2.487.jar : crafttweaker (7.1.2.487) - 1
• mods_folder Mekanism-1.16.5-10.1.1.456.jar : mekanism (10.1.1) - 1
• mods_folder rftoolspower-1.16-3.0.11.jar : rftoolspower (1.16-3.0.11) - 1
• maven_libs forge-1.16.5-36.2.23-universal.jar : forge (36.2.23) - 1
• mods_folder Waddles-1.16.5-0.8.13.jar : waddles (1.16.5-0.8.13) - 1
• mods_folder iskallutilities-1.4.jar : iskallutilities (1.4) - 1
• mods_folder selene-1.16.5-1.9.0.jar : selene (1.16.5-1.0) - 1
• mods_folder ironchest-1.16.5-11.2.21.jar : ironchest (1.16.5-11.2.21) - 1
• minecraft forge-1.16.5-36.2.23-server.jar : minecraft (1.16.5) - 1
• mods_folder cofh_core-1.16.5-1.4.0.6.jar : cofh_core (1.4.0.6) - 1
• mods_folder thermal_foundation-1.16.5-1.4.1.7.jar : thermal (1.4.1.7) - 2
• mods_folder thermal_expansion-1.16.5-1.4.1.3.jar : thermal_expansion (1.4.1.3) - 1
• mods_folder rftoolsutility-1.16-3.1.7.jar : rftoolsutility (1.16-3.1.7) - 1
• mods_folder Dynmap-3.2.1-forge-1.16.5.jar : dynmap (3.2.1-531) - 1
• mods_folder MouseTweaks-2.14-mc1.16.2.jar : mousetweaks (2.14) - 1
• mods_folder titanium-1.16.5-3.2.8.4-10.jar : titanium (3.2.8.4) - 1
• mods_folder ImmersiveEngineering-1.16.5-5.0.7-143.jar : immersiveengineering (1.16.5-5.0.7-143) - 1
• mods_folder useful_railroads-1.16.5-1.4.6.38.jar : usefulrailroads (1.4.6.38) - 1
• mods_folder movingelevators-1.2.34-mc1.16.5.jar : movingelevators (1.2.34) - 1
• mods_folder archers_paradox-1.16.5-1.4.0.1.jar : archers_paradox (1.4.0.1) - 1
• mods_folder storage_overhaul-1.16.5-1.0.4.jar : storage_overhaul (1.16.5-1.0.4) - 1
• mods_folder CreateTweaker-1.0.0.26.jar : createtweaker (1.0.0.26) - 1
• mods_folder rftoolsbuilder-1.16-3.1.4.jar : rftoolsbuilder (1.16-3.1.4) - 1
• mods_folder jeiintegration_1.16.5-7.0.1.15.jar : jeiintegration (7.0.1.15) - 1
• mods_folder easy_villagers-1.16.5-1.0.11.jar : easy_villagers (1.16.5-1.0.11) - 1
• mods_folder flywheel-1.16-0.2.5.jar : flywheel (1.16-0.2.5) - 1
• mods_folder create-mc1.16.5_v0.3.2g.jar : create (v0.3.2g) - 1
• mods_folder Xaeros_Minimap_21.14.1_Forge_1.16.5.jar : xaerominimap (21.14.1) - 1
• mods_folder ftb-backups-2.1.2.2.jar : ftbbackups (2.1.2.2) - 1
• mods_folder FastWorkbench-1.16.5-4.6.1.jar : fastbench (4.6.1) - 1
• mods_folder AutoRegLib-1.6-49.jar : autoreglib (1.6-49) - 1
• mods_folder Quark-r2.4-321.jar : quark (r2.4-321) - 1
• mods_folder StorageDrawers-1.16.3-8.5.0.jar : storagedrawers (8.5.0) - 1
• mods_folder FluxNetworks-1.16.5-6.1.7.12.jar : fluxnetworks (6.1.7.12) - 1
• mods_folder whitelistsync2-1.16.5-2.2.5.jar : whitelistsync2 (version) - 1
• mods_folder appleskin-forge-mc1.16.x-2.2.0.jar : appleskin (mc1.16.4-2.2.0) - 1
• mods_folder engineersdecor-1.16.5-1.1.15.jar : engineersdecor (1.1.15) - 1
• mods_folder modular-routers-1.16.5-7.4.0-55.jar : modularrouters (task ':jar' property 'archiveVersion') - 1
• mods_folder byg-1.3.5.jar : byg (1.3.4) - 1
• mods_folder refinedstorageaddons-0.7.3.jar : refinedstorageaddons (0.7.3) - 1
• mods_folder OpenLoader-1.16.5-9.0.3.jar : openloader (9.0.3) - 1
• mods_folder EnderMail-1.16.5-1.2.2.jar : endermail (1.16.5-1.2.2) - 1
• mods_folder the_vault-1.7.2p1.12.4.jar : the_vault (1.7.2p1.12.4) - 1

**Comment by jordankothe9** [comment]
Please see Pull Request #20 as a possible solution

**Comment by PotatoSauceVFX** [comment]
Thank you for your contribution. I will have a release jar out soon with these changes!
