### ISSUE TITLE
Latest version requires client side installation?

### ISSUE THREAD

**Issue by igotfits1** [PotatoSauceVFX/Whitelist-Sync-2#25]
![unknown](https://user-images.githubusercontent.com/31754401/171050118-74d57cb8-31f8-4c84-87ac-27fa46c2b18f.png)
Hi, alot of clients now cant join without an error that says client is missing whitelist sync 2.0 mod for 1.12.2

**Comment by PotatoSauceVFX** [comment]
Is this specific to the 1.12.2 version?

**Comment by igotfits1** [comment]
sofar yea, ive updated 1.16 and 1.12

**Comment by PotatoSauceVFX** [comment]
Alright, I will have a fix up in about 5min.

**Comment by PotatoSauceVFX** [comment]
Fixed in 1.12.2-2.4.1

**Comment by igotfits1** [comment]
:D ty, super fast!
