### ISSUE TITLE
latest beta cannot connect to any mysql server

### ISSUE THREAD

**Issue by unknownuser2019** [PotatoSauceVFX/Whitelist-Sync-2#6]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Whitelist Sync 2.0 (whitelistsync2)
Caused by: com.potatosaucevfx.whitelistsync2.exceptions.MySqlDbError: Failed to connect to the mySQL database! Did you set one up in the config?
No suitable driver found for jdbc:mysql://localhost:3306/?serverTimezone=UTC

(database is connected and created for local and remote services and still errors out

**Comment by PotatoSauceVFX** [comment]
Yeah.. I forgot to add that to the documentation. For some reason Shadow stopped including the mod dependencies in the compiled jar. If you download [mysql-connector-java](http://central.maven.org/maven2/mysql/mysql-connector-java/8.0.8-dmr/mysql-connector-java-8.0.8-dmr.jar) and [json-simple](http://central.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar) add them in your mods folder, it should be fixed. I am planning on fixing this in the release. My apologies.

**Comment by unknownuser2019** [comment]
Yea, that fixed that and allowed me to connect my remote SQL DB for WL/WLOPS commands

**Comment by PotatoSauceVFX** [comment]
I have also had issues with wlop and MySQL so just be aware. It is just a beta.

**Comment by unknownuser2019** [comment]
I understand that its fun though messing around setting up 12 different modpacks on two different servers while setting up remote MySQL DB access

**Comment by PotatoSauceVFX** [comment]
Yeah, personally I haven't tried anything like that. Test the hell out of it! 😁

**Comment by unknownuser2019** [comment]
Will Do :P
